<?php

// @generated by generate-docs.php. Do not edit.
// This file is for IDE autocompletion.

namespace Oqs;

// --- Global Constants ---
/** @var integer Version information from the underlying liboqs library. */
const VERSION_MAJOR = 0;

/** @var integer Version information from the underlying liboqs library. */
const VERSION_MINOR = 16;

/** @var integer Version information from the underlying liboqs library. */
const VERSION_PATCH = 0;

/** @var string Version information from the underlying liboqs library. */
const VERSION_TEXT = '0.16.0';

class Exception extends \Exception {}

final class Kem
{
    /** @var string The "BIKE-L1" algorithm. */
    public const ALG_BIKE_L1 = 'BIKE-L1';

    /** @var string The "BIKE-L3" algorithm. */
    public const ALG_BIKE_L3 = 'BIKE-L3';

    /** @var string The "BIKE-L5" algorithm. */
    public const ALG_BIKE_L5 = 'BIKE-L5';

    /** @var string The "Classic-McEliece-348864" algorithm. */
    public const ALG_CLASSIC_MCELIECE_348864 = 'Classic-McEliece-348864';

    /** @var string The "Classic-McEliece-348864f" algorithm. */
    public const ALG_CLASSIC_MCELIECE_348864F = 'Classic-McEliece-348864f';

    /** @var string The "Classic-McEliece-460896" algorithm. */
    public const ALG_CLASSIC_MCELIECE_460896 = 'Classic-McEliece-460896';

    /** @var string The "Classic-McEliece-460896f" algorithm. */
    public const ALG_CLASSIC_MCELIECE_460896F = 'Classic-McEliece-460896f';

    /** @var string The "Classic-McEliece-6688128" algorithm. */
    public const ALG_CLASSIC_MCELIECE_6688128 = 'Classic-McEliece-6688128';

    /** @var string The "Classic-McEliece-6688128f" algorithm. */
    public const ALG_CLASSIC_MCELIECE_6688128F = 'Classic-McEliece-6688128f';

    /** @var string The "Classic-McEliece-6960119" algorithm. */
    public const ALG_CLASSIC_MCELIECE_6960119 = 'Classic-McEliece-6960119';

    /** @var string The "Classic-McEliece-6960119f" algorithm. */
    public const ALG_CLASSIC_MCELIECE_6960119F = 'Classic-McEliece-6960119f';

    /** @var string The "Classic-McEliece-8192128" algorithm. */
    public const ALG_CLASSIC_MCELIECE_8192128 = 'Classic-McEliece-8192128';

    /** @var string The "Classic-McEliece-8192128f" algorithm. */
    public const ALG_CLASSIC_MCELIECE_8192128F = 'Classic-McEliece-8192128f';

    /** @var string The "eFrodoKEM-1344-AES" algorithm. */
    public const ALG_EFRODOKEM_1344_AES = 'eFrodoKEM-1344-AES';

    /** @var string The "eFrodoKEM-1344-SHAKE" algorithm. */
    public const ALG_EFRODOKEM_1344_SHAKE = 'eFrodoKEM-1344-SHAKE';

    /** @var string The "eFrodoKEM-640-AES" algorithm. */
    public const ALG_EFRODOKEM_640_AES = 'eFrodoKEM-640-AES';

    /** @var string The "eFrodoKEM-640-SHAKE" algorithm. */
    public const ALG_EFRODOKEM_640_SHAKE = 'eFrodoKEM-640-SHAKE';

    /** @var string The "eFrodoKEM-976-AES" algorithm. */
    public const ALG_EFRODOKEM_976_AES = 'eFrodoKEM-976-AES';

    /** @var string The "eFrodoKEM-976-SHAKE" algorithm. */
    public const ALG_EFRODOKEM_976_SHAKE = 'eFrodoKEM-976-SHAKE';

    /** @var string The "FrodoKEM-1344-AES" algorithm. */
    public const ALG_FRODOKEM_1344_AES = 'FrodoKEM-1344-AES';

    /** @var string The "FrodoKEM-1344-SHAKE" algorithm. */
    public const ALG_FRODOKEM_1344_SHAKE = 'FrodoKEM-1344-SHAKE';

    /** @var string The "FrodoKEM-640-AES" algorithm. */
    public const ALG_FRODOKEM_640_AES = 'FrodoKEM-640-AES';

    /** @var string The "FrodoKEM-640-SHAKE" algorithm. */
    public const ALG_FRODOKEM_640_SHAKE = 'FrodoKEM-640-SHAKE';

    /** @var string The "FrodoKEM-976-AES" algorithm. */
    public const ALG_FRODOKEM_976_AES = 'FrodoKEM-976-AES';

    /** @var string The "FrodoKEM-976-SHAKE" algorithm. */
    public const ALG_FRODOKEM_976_SHAKE = 'FrodoKEM-976-SHAKE';

    /** @var string The "HQC-1" algorithm. */
    public const ALG_HQC_1 = 'HQC-1';

    /** @var string The "HQC-3" algorithm. */
    public const ALG_HQC_3 = 'HQC-3';

    /** @var string The "HQC-5" algorithm. */
    public const ALG_HQC_5 = 'HQC-5';

    /** @var string The "Kyber1024" algorithm. */
    public const ALG_KYBER1024 = 'Kyber1024';

    /** @var string The "Kyber512" algorithm. */
    public const ALG_KYBER512 = 'Kyber512';

    /** @var string The "Kyber768" algorithm. */
    public const ALG_KYBER768 = 'Kyber768';

    /** @var string The "ML-KEM-1024" algorithm. */
    public const ALG_ML_KEM_1024 = 'ML-KEM-1024';

    /** @var string The "ML-KEM-512" algorithm. */
    public const ALG_ML_KEM_512 = 'ML-KEM-512';

    /** @var string The "ML-KEM-768" algorithm. */
    public const ALG_ML_KEM_768 = 'ML-KEM-768';

    /** @var string The "NTRU-HPS-2048-509" algorithm. */
    public const ALG_NTRU_HPS_2048_509 = 'NTRU-HPS-2048-509';

    /** @var string The "NTRU-HPS-2048-677" algorithm. */
    public const ALG_NTRU_HPS_2048_677 = 'NTRU-HPS-2048-677';

    /** @var string The "NTRU-HPS-4096-1229" algorithm. */
    public const ALG_NTRU_HPS_4096_1229 = 'NTRU-HPS-4096-1229';

    /** @var string The "NTRU-HPS-4096-821" algorithm. */
    public const ALG_NTRU_HPS_4096_821 = 'NTRU-HPS-4096-821';

    /** @var string The "NTRU-HRSS-1373" algorithm. */
    public const ALG_NTRU_HRSS_1373 = 'NTRU-HRSS-1373';

    /** @var string The "NTRU-HRSS-701" algorithm. */
    public const ALG_NTRU_HRSS_701 = 'NTRU-HRSS-701';

    /** @var string The "sntrup761" algorithm. */
    public const ALG_SNTRUP761 = 'sntrup761';

    /**
     * @param string $algorithm
     */
    public function __construct(string $algorithm) {}

    /**
     * @return array
     */
    public function sizes(): array {}

    /**
     * @return array
     */
    public function keypair(): array {}

    /**
     * @param string $publicKey
     * @return array
     */
    public function encap(string $publicKey): array {}

    /**
     * @param string $ciphertext
     * @param string $secretKey
     * @return string
     */
    public function decap(string $ciphertext, string $secretKey): string {}

    /**
     * @return array
     */
    public function details(): array {}

    /**
     * @return array
     */
    public static function algorithms(): array {}

}
final class Sig
{
    /** @var string The "cross-rsdpg-128-balanced" algorithm. */
    public const ALG_CROSS_RSDPG_128_BALANCED = 'cross-rsdpg-128-balanced';

    /** @var string The "cross-rsdpg-128-fast" algorithm. */
    public const ALG_CROSS_RSDPG_128_FAST = 'cross-rsdpg-128-fast';

    /** @var string The "cross-rsdpg-128-small" algorithm. */
    public const ALG_CROSS_RSDPG_128_SMALL = 'cross-rsdpg-128-small';

    /** @var string The "cross-rsdpg-192-balanced" algorithm. */
    public const ALG_CROSS_RSDPG_192_BALANCED = 'cross-rsdpg-192-balanced';

    /** @var string The "cross-rsdpg-192-fast" algorithm. */
    public const ALG_CROSS_RSDPG_192_FAST = 'cross-rsdpg-192-fast';

    /** @var string The "cross-rsdpg-192-small" algorithm. */
    public const ALG_CROSS_RSDPG_192_SMALL = 'cross-rsdpg-192-small';

    /** @var string The "cross-rsdpg-256-balanced" algorithm. */
    public const ALG_CROSS_RSDPG_256_BALANCED = 'cross-rsdpg-256-balanced';

    /** @var string The "cross-rsdpg-256-fast" algorithm. */
    public const ALG_CROSS_RSDPG_256_FAST = 'cross-rsdpg-256-fast';

    /** @var string The "cross-rsdpg-256-small" algorithm. */
    public const ALG_CROSS_RSDPG_256_SMALL = 'cross-rsdpg-256-small';

    /** @var string The "cross-rsdp-128-balanced" algorithm. */
    public const ALG_CROSS_RSDP_128_BALANCED = 'cross-rsdp-128-balanced';

    /** @var string The "cross-rsdp-128-fast" algorithm. */
    public const ALG_CROSS_RSDP_128_FAST = 'cross-rsdp-128-fast';

    /** @var string The "cross-rsdp-128-small" algorithm. */
    public const ALG_CROSS_RSDP_128_SMALL = 'cross-rsdp-128-small';

    /** @var string The "cross-rsdp-192-balanced" algorithm. */
    public const ALG_CROSS_RSDP_192_BALANCED = 'cross-rsdp-192-balanced';

    /** @var string The "cross-rsdp-192-fast" algorithm. */
    public const ALG_CROSS_RSDP_192_FAST = 'cross-rsdp-192-fast';

    /** @var string The "cross-rsdp-192-small" algorithm. */
    public const ALG_CROSS_RSDP_192_SMALL = 'cross-rsdp-192-small';

    /** @var string The "cross-rsdp-256-balanced" algorithm. */
    public const ALG_CROSS_RSDP_256_BALANCED = 'cross-rsdp-256-balanced';

    /** @var string The "cross-rsdp-256-fast" algorithm. */
    public const ALG_CROSS_RSDP_256_FAST = 'cross-rsdp-256-fast';

    /** @var string The "cross-rsdp-256-small" algorithm. */
    public const ALG_CROSS_RSDP_256_SMALL = 'cross-rsdp-256-small';

    /** @var string The "Falcon-1024" algorithm. */
    public const ALG_FALCON_1024 = 'Falcon-1024';

    /** @var string The "Falcon-512" algorithm. */
    public const ALG_FALCON_512 = 'Falcon-512';

    /** @var string The "Falcon-padded-1024" algorithm. */
    public const ALG_FALCON_PADDED_1024 = 'Falcon-padded-1024';

    /** @var string The "Falcon-padded-512" algorithm. */
    public const ALG_FALCON_PADDED_512 = 'Falcon-padded-512';

    /** @var string The "MAYO-1" algorithm. */
    public const ALG_MAYO_1 = 'MAYO-1';

    /** @var string The "MAYO-2" algorithm. */
    public const ALG_MAYO_2 = 'MAYO-2';

    /** @var string The "MAYO-3" algorithm. */
    public const ALG_MAYO_3 = 'MAYO-3';

    /** @var string The "MAYO-5" algorithm. */
    public const ALG_MAYO_5 = 'MAYO-5';

    /** @var string The "ML-DSA-44" algorithm. */
    public const ALG_ML_DSA_44 = 'ML-DSA-44';

    /** @var string The "ML-DSA-65" algorithm. */
    public const ALG_ML_DSA_65 = 'ML-DSA-65';

    /** @var string The "ML-DSA-87" algorithm. */
    public const ALG_ML_DSA_87 = 'ML-DSA-87';

    /** @var string The "mqom2_cat1_gf16_fast_r3" algorithm. */
    public const ALG_MQOM2_CAT1_GF16_FAST_R3 = 'mqom2_cat1_gf16_fast_r3';

    /** @var string The "mqom2_cat1_gf16_fast_r5" algorithm. */
    public const ALG_MQOM2_CAT1_GF16_FAST_R5 = 'mqom2_cat1_gf16_fast_r5';

    /** @var string The "mqom2_cat1_gf16_short_r3" algorithm. */
    public const ALG_MQOM2_CAT1_GF16_SHORT_R3 = 'mqom2_cat1_gf16_short_r3';

    /** @var string The "mqom2_cat1_gf16_short_r5" algorithm. */
    public const ALG_MQOM2_CAT1_GF16_SHORT_R5 = 'mqom2_cat1_gf16_short_r5';

    /** @var string The "mqom2_cat3_gf16_fast_r3" algorithm. */
    public const ALG_MQOM2_CAT3_GF16_FAST_R3 = 'mqom2_cat3_gf16_fast_r3';

    /** @var string The "mqom2_cat3_gf16_fast_r5" algorithm. */
    public const ALG_MQOM2_CAT3_GF16_FAST_R5 = 'mqom2_cat3_gf16_fast_r5';

    /** @var string The "mqom2_cat3_gf16_short_r3" algorithm. */
    public const ALG_MQOM2_CAT3_GF16_SHORT_R3 = 'mqom2_cat3_gf16_short_r3';

    /** @var string The "mqom2_cat3_gf16_short_r5" algorithm. */
    public const ALG_MQOM2_CAT3_GF16_SHORT_R5 = 'mqom2_cat3_gf16_short_r5';

    /** @var string The "mqom2_cat5_gf16_fast_r3" algorithm. */
    public const ALG_MQOM2_CAT5_GF16_FAST_R3 = 'mqom2_cat5_gf16_fast_r3';

    /** @var string The "mqom2_cat5_gf16_fast_r5" algorithm. */
    public const ALG_MQOM2_CAT5_GF16_FAST_R5 = 'mqom2_cat5_gf16_fast_r5';

    /** @var string The "mqom2_cat5_gf16_short_r3" algorithm. */
    public const ALG_MQOM2_CAT5_GF16_SHORT_R3 = 'mqom2_cat5_gf16_short_r3';

    /** @var string The "mqom2_cat5_gf16_short_r5" algorithm. */
    public const ALG_MQOM2_CAT5_GF16_SHORT_R5 = 'mqom2_cat5_gf16_short_r5';

    /** @var string The "OV-III" algorithm. */
    public const ALG_OV_III = 'OV-III';

    /** @var string The "OV-III-pkc" algorithm. */
    public const ALG_OV_III_PKC = 'OV-III-pkc';

    /** @var string The "OV-III-pkc-skc" algorithm. */
    public const ALG_OV_III_PKC_SKC = 'OV-III-pkc-skc';

    /** @var string The "OV-Ip" algorithm. */
    public const ALG_OV_IP = 'OV-Ip';

    /** @var string The "OV-Ip-pkc" algorithm. */
    public const ALG_OV_IP_PKC = 'OV-Ip-pkc';

    /** @var string The "OV-Ip-pkc-skc" algorithm. */
    public const ALG_OV_IP_PKC_SKC = 'OV-Ip-pkc-skc';

    /** @var string The "OV-Is" algorithm. */
    public const ALG_OV_IS = 'OV-Is';

    /** @var string The "OV-Is-pkc" algorithm. */
    public const ALG_OV_IS_PKC = 'OV-Is-pkc';

    /** @var string The "OV-Is-pkc-skc" algorithm. */
    public const ALG_OV_IS_PKC_SKC = 'OV-Is-pkc-skc';

    /** @var string The "OV-V" algorithm. */
    public const ALG_OV_V = 'OV-V';

    /** @var string The "OV-V-pkc" algorithm. */
    public const ALG_OV_V_PKC = 'OV-V-pkc';

    /** @var string The "OV-V-pkc-skc" algorithm. */
    public const ALG_OV_V_PKC_SKC = 'OV-V-pkc-skc';

    /** @var string The "SLH_DSA_PURE_SHA2_128F" algorithm. */
    public const ALG_SLH_DSA_PURE_SHA2_128F = 'SLH_DSA_PURE_SHA2_128F';

    /** @var string The "SLH_DSA_PURE_SHA2_128S" algorithm. */
    public const ALG_SLH_DSA_PURE_SHA2_128S = 'SLH_DSA_PURE_SHA2_128S';

    /** @var string The "SLH_DSA_PURE_SHA2_192F" algorithm. */
    public const ALG_SLH_DSA_PURE_SHA2_192F = 'SLH_DSA_PURE_SHA2_192F';

    /** @var string The "SLH_DSA_PURE_SHA2_192S" algorithm. */
    public const ALG_SLH_DSA_PURE_SHA2_192S = 'SLH_DSA_PURE_SHA2_192S';

    /** @var string The "SLH_DSA_PURE_SHA2_256F" algorithm. */
    public const ALG_SLH_DSA_PURE_SHA2_256F = 'SLH_DSA_PURE_SHA2_256F';

    /** @var string The "SLH_DSA_PURE_SHA2_256S" algorithm. */
    public const ALG_SLH_DSA_PURE_SHA2_256S = 'SLH_DSA_PURE_SHA2_256S';

    /** @var string The "SLH_DSA_PURE_SHAKE_128F" algorithm. */
    public const ALG_SLH_DSA_PURE_SHAKE_128F = 'SLH_DSA_PURE_SHAKE_128F';

    /** @var string The "SLH_DSA_PURE_SHAKE_128S" algorithm. */
    public const ALG_SLH_DSA_PURE_SHAKE_128S = 'SLH_DSA_PURE_SHAKE_128S';

    /** @var string The "SLH_DSA_PURE_SHAKE_192F" algorithm. */
    public const ALG_SLH_DSA_PURE_SHAKE_192F = 'SLH_DSA_PURE_SHAKE_192F';

    /** @var string The "SLH_DSA_PURE_SHAKE_192S" algorithm. */
    public const ALG_SLH_DSA_PURE_SHAKE_192S = 'SLH_DSA_PURE_SHAKE_192S';

    /** @var string The "SLH_DSA_PURE_SHAKE_256F" algorithm. */
    public const ALG_SLH_DSA_PURE_SHAKE_256F = 'SLH_DSA_PURE_SHAKE_256F';

    /** @var string The "SLH_DSA_PURE_SHAKE_256S" algorithm. */
    public const ALG_SLH_DSA_PURE_SHAKE_256S = 'SLH_DSA_PURE_SHAKE_256S';

    /** @var string The "SLH_DSA_SHA2_224_PREHASH_SHA2_128F" algorithm. */
    public const ALG_SLH_DSA_SHA2_224_PREHASH_SHA2_128F = 'SLH_DSA_SHA2_224_PREHASH_SHA2_128F';

    /** @var string The "SLH_DSA_SHA2_224_PREHASH_SHA2_128S" algorithm. */
    public const ALG_SLH_DSA_SHA2_224_PREHASH_SHA2_128S = 'SLH_DSA_SHA2_224_PREHASH_SHA2_128S';

    /** @var string The "SLH_DSA_SHA2_224_PREHASH_SHA2_192F" algorithm. */
    public const ALG_SLH_DSA_SHA2_224_PREHASH_SHA2_192F = 'SLH_DSA_SHA2_224_PREHASH_SHA2_192F';

    /** @var string The "SLH_DSA_SHA2_224_PREHASH_SHA2_192S" algorithm. */
    public const ALG_SLH_DSA_SHA2_224_PREHASH_SHA2_192S = 'SLH_DSA_SHA2_224_PREHASH_SHA2_192S';

    /** @var string The "SLH_DSA_SHA2_224_PREHASH_SHA2_256F" algorithm. */
    public const ALG_SLH_DSA_SHA2_224_PREHASH_SHA2_256F = 'SLH_DSA_SHA2_224_PREHASH_SHA2_256F';

    /** @var string The "SLH_DSA_SHA2_224_PREHASH_SHA2_256S" algorithm. */
    public const ALG_SLH_DSA_SHA2_224_PREHASH_SHA2_256S = 'SLH_DSA_SHA2_224_PREHASH_SHA2_256S';

    /** @var string The "SLH_DSA_SHA2_224_PREHASH_SHAKE_128F" algorithm. */
    public const ALG_SLH_DSA_SHA2_224_PREHASH_SHAKE_128F = 'SLH_DSA_SHA2_224_PREHASH_SHAKE_128F';

    /** @var string The "SLH_DSA_SHA2_224_PREHASH_SHAKE_128S" algorithm. */
    public const ALG_SLH_DSA_SHA2_224_PREHASH_SHAKE_128S = 'SLH_DSA_SHA2_224_PREHASH_SHAKE_128S';

    /** @var string The "SLH_DSA_SHA2_224_PREHASH_SHAKE_192F" algorithm. */
    public const ALG_SLH_DSA_SHA2_224_PREHASH_SHAKE_192F = 'SLH_DSA_SHA2_224_PREHASH_SHAKE_192F';

    /** @var string The "SLH_DSA_SHA2_224_PREHASH_SHAKE_192S" algorithm. */
    public const ALG_SLH_DSA_SHA2_224_PREHASH_SHAKE_192S = 'SLH_DSA_SHA2_224_PREHASH_SHAKE_192S';

    /** @var string The "SLH_DSA_SHA2_224_PREHASH_SHAKE_256F" algorithm. */
    public const ALG_SLH_DSA_SHA2_224_PREHASH_SHAKE_256F = 'SLH_DSA_SHA2_224_PREHASH_SHAKE_256F';

    /** @var string The "SLH_DSA_SHA2_224_PREHASH_SHAKE_256S" algorithm. */
    public const ALG_SLH_DSA_SHA2_224_PREHASH_SHAKE_256S = 'SLH_DSA_SHA2_224_PREHASH_SHAKE_256S';

    /** @var string The "SLH_DSA_SHA2_256_PREHASH_SHA2_128F" algorithm. */
    public const ALG_SLH_DSA_SHA2_256_PREHASH_SHA2_128F = 'SLH_DSA_SHA2_256_PREHASH_SHA2_128F';

    /** @var string The "SLH_DSA_SHA2_256_PREHASH_SHA2_128S" algorithm. */
    public const ALG_SLH_DSA_SHA2_256_PREHASH_SHA2_128S = 'SLH_DSA_SHA2_256_PREHASH_SHA2_128S';

    /** @var string The "SLH_DSA_SHA2_256_PREHASH_SHA2_192F" algorithm. */
    public const ALG_SLH_DSA_SHA2_256_PREHASH_SHA2_192F = 'SLH_DSA_SHA2_256_PREHASH_SHA2_192F';

    /** @var string The "SLH_DSA_SHA2_256_PREHASH_SHA2_192S" algorithm. */
    public const ALG_SLH_DSA_SHA2_256_PREHASH_SHA2_192S = 'SLH_DSA_SHA2_256_PREHASH_SHA2_192S';

    /** @var string The "SLH_DSA_SHA2_256_PREHASH_SHA2_256F" algorithm. */
    public const ALG_SLH_DSA_SHA2_256_PREHASH_SHA2_256F = 'SLH_DSA_SHA2_256_PREHASH_SHA2_256F';

    /** @var string The "SLH_DSA_SHA2_256_PREHASH_SHA2_256S" algorithm. */
    public const ALG_SLH_DSA_SHA2_256_PREHASH_SHA2_256S = 'SLH_DSA_SHA2_256_PREHASH_SHA2_256S';

    /** @var string The "SLH_DSA_SHA2_256_PREHASH_SHAKE_128F" algorithm. */
    public const ALG_SLH_DSA_SHA2_256_PREHASH_SHAKE_128F = 'SLH_DSA_SHA2_256_PREHASH_SHAKE_128F';

    /** @var string The "SLH_DSA_SHA2_256_PREHASH_SHAKE_128S" algorithm. */
    public const ALG_SLH_DSA_SHA2_256_PREHASH_SHAKE_128S = 'SLH_DSA_SHA2_256_PREHASH_SHAKE_128S';

    /** @var string The "SLH_DSA_SHA2_256_PREHASH_SHAKE_192F" algorithm. */
    public const ALG_SLH_DSA_SHA2_256_PREHASH_SHAKE_192F = 'SLH_DSA_SHA2_256_PREHASH_SHAKE_192F';

    /** @var string The "SLH_DSA_SHA2_256_PREHASH_SHAKE_192S" algorithm. */
    public const ALG_SLH_DSA_SHA2_256_PREHASH_SHAKE_192S = 'SLH_DSA_SHA2_256_PREHASH_SHAKE_192S';

    /** @var string The "SLH_DSA_SHA2_256_PREHASH_SHAKE_256F" algorithm. */
    public const ALG_SLH_DSA_SHA2_256_PREHASH_SHAKE_256F = 'SLH_DSA_SHA2_256_PREHASH_SHAKE_256F';

    /** @var string The "SLH_DSA_SHA2_256_PREHASH_SHAKE_256S" algorithm. */
    public const ALG_SLH_DSA_SHA2_256_PREHASH_SHAKE_256S = 'SLH_DSA_SHA2_256_PREHASH_SHAKE_256S';

    /** @var string The "SLH_DSA_SHA2_384_PREHASH_SHA2_128F" algorithm. */
    public const ALG_SLH_DSA_SHA2_384_PREHASH_SHA2_128F = 'SLH_DSA_SHA2_384_PREHASH_SHA2_128F';

    /** @var string The "SLH_DSA_SHA2_384_PREHASH_SHA2_128S" algorithm. */
    public const ALG_SLH_DSA_SHA2_384_PREHASH_SHA2_128S = 'SLH_DSA_SHA2_384_PREHASH_SHA2_128S';

    /** @var string The "SLH_DSA_SHA2_384_PREHASH_SHA2_192F" algorithm. */
    public const ALG_SLH_DSA_SHA2_384_PREHASH_SHA2_192F = 'SLH_DSA_SHA2_384_PREHASH_SHA2_192F';

    /** @var string The "SLH_DSA_SHA2_384_PREHASH_SHA2_192S" algorithm. */
    public const ALG_SLH_DSA_SHA2_384_PREHASH_SHA2_192S = 'SLH_DSA_SHA2_384_PREHASH_SHA2_192S';

    /** @var string The "SLH_DSA_SHA2_384_PREHASH_SHA2_256F" algorithm. */
    public const ALG_SLH_DSA_SHA2_384_PREHASH_SHA2_256F = 'SLH_DSA_SHA2_384_PREHASH_SHA2_256F';

    /** @var string The "SLH_DSA_SHA2_384_PREHASH_SHA2_256S" algorithm. */
    public const ALG_SLH_DSA_SHA2_384_PREHASH_SHA2_256S = 'SLH_DSA_SHA2_384_PREHASH_SHA2_256S';

    /** @var string The "SLH_DSA_SHA2_384_PREHASH_SHAKE_128F" algorithm. */
    public const ALG_SLH_DSA_SHA2_384_PREHASH_SHAKE_128F = 'SLH_DSA_SHA2_384_PREHASH_SHAKE_128F';

    /** @var string The "SLH_DSA_SHA2_384_PREHASH_SHAKE_128S" algorithm. */
    public const ALG_SLH_DSA_SHA2_384_PREHASH_SHAKE_128S = 'SLH_DSA_SHA2_384_PREHASH_SHAKE_128S';

    /** @var string The "SLH_DSA_SHA2_384_PREHASH_SHAKE_192F" algorithm. */
    public const ALG_SLH_DSA_SHA2_384_PREHASH_SHAKE_192F = 'SLH_DSA_SHA2_384_PREHASH_SHAKE_192F';

    /** @var string The "SLH_DSA_SHA2_384_PREHASH_SHAKE_192S" algorithm. */
    public const ALG_SLH_DSA_SHA2_384_PREHASH_SHAKE_192S = 'SLH_DSA_SHA2_384_PREHASH_SHAKE_192S';

    /** @var string The "SLH_DSA_SHA2_384_PREHASH_SHAKE_256F" algorithm. */
    public const ALG_SLH_DSA_SHA2_384_PREHASH_SHAKE_256F = 'SLH_DSA_SHA2_384_PREHASH_SHAKE_256F';

    /** @var string The "SLH_DSA_SHA2_384_PREHASH_SHAKE_256S" algorithm. */
    public const ALG_SLH_DSA_SHA2_384_PREHASH_SHAKE_256S = 'SLH_DSA_SHA2_384_PREHASH_SHAKE_256S';

    /** @var string The "SLH_DSA_SHA2_512_224_PREHASH_SHA2_128F" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_224_PREHASH_SHA2_128F = 'SLH_DSA_SHA2_512_224_PREHASH_SHA2_128F';

    /** @var string The "SLH_DSA_SHA2_512_224_PREHASH_SHA2_128S" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_224_PREHASH_SHA2_128S = 'SLH_DSA_SHA2_512_224_PREHASH_SHA2_128S';

    /** @var string The "SLH_DSA_SHA2_512_224_PREHASH_SHA2_192F" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_224_PREHASH_SHA2_192F = 'SLH_DSA_SHA2_512_224_PREHASH_SHA2_192F';

    /** @var string The "SLH_DSA_SHA2_512_224_PREHASH_SHA2_192S" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_224_PREHASH_SHA2_192S = 'SLH_DSA_SHA2_512_224_PREHASH_SHA2_192S';

    /** @var string The "SLH_DSA_SHA2_512_224_PREHASH_SHA2_256F" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_224_PREHASH_SHA2_256F = 'SLH_DSA_SHA2_512_224_PREHASH_SHA2_256F';

    /** @var string The "SLH_DSA_SHA2_512_224_PREHASH_SHA2_256S" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_224_PREHASH_SHA2_256S = 'SLH_DSA_SHA2_512_224_PREHASH_SHA2_256S';

    /** @var string The "SLH_DSA_SHA2_512_224_PREHASH_SHAKE_128F" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_224_PREHASH_SHAKE_128F = 'SLH_DSA_SHA2_512_224_PREHASH_SHAKE_128F';

    /** @var string The "SLH_DSA_SHA2_512_224_PREHASH_SHAKE_128S" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_224_PREHASH_SHAKE_128S = 'SLH_DSA_SHA2_512_224_PREHASH_SHAKE_128S';

    /** @var string The "SLH_DSA_SHA2_512_224_PREHASH_SHAKE_192F" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_224_PREHASH_SHAKE_192F = 'SLH_DSA_SHA2_512_224_PREHASH_SHAKE_192F';

    /** @var string The "SLH_DSA_SHA2_512_224_PREHASH_SHAKE_192S" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_224_PREHASH_SHAKE_192S = 'SLH_DSA_SHA2_512_224_PREHASH_SHAKE_192S';

    /** @var string The "SLH_DSA_SHA2_512_224_PREHASH_SHAKE_256F" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_224_PREHASH_SHAKE_256F = 'SLH_DSA_SHA2_512_224_PREHASH_SHAKE_256F';

    /** @var string The "SLH_DSA_SHA2_512_224_PREHASH_SHAKE_256S" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_224_PREHASH_SHAKE_256S = 'SLH_DSA_SHA2_512_224_PREHASH_SHAKE_256S';

    /** @var string The "SLH_DSA_SHA2_512_256_PREHASH_SHA2_128F" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_256_PREHASH_SHA2_128F = 'SLH_DSA_SHA2_512_256_PREHASH_SHA2_128F';

    /** @var string The "SLH_DSA_SHA2_512_256_PREHASH_SHA2_128S" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_256_PREHASH_SHA2_128S = 'SLH_DSA_SHA2_512_256_PREHASH_SHA2_128S';

    /** @var string The "SLH_DSA_SHA2_512_256_PREHASH_SHA2_192F" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_256_PREHASH_SHA2_192F = 'SLH_DSA_SHA2_512_256_PREHASH_SHA2_192F';

    /** @var string The "SLH_DSA_SHA2_512_256_PREHASH_SHA2_192S" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_256_PREHASH_SHA2_192S = 'SLH_DSA_SHA2_512_256_PREHASH_SHA2_192S';

    /** @var string The "SLH_DSA_SHA2_512_256_PREHASH_SHA2_256F" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_256_PREHASH_SHA2_256F = 'SLH_DSA_SHA2_512_256_PREHASH_SHA2_256F';

    /** @var string The "SLH_DSA_SHA2_512_256_PREHASH_SHA2_256S" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_256_PREHASH_SHA2_256S = 'SLH_DSA_SHA2_512_256_PREHASH_SHA2_256S';

    /** @var string The "SLH_DSA_SHA2_512_256_PREHASH_SHAKE_128F" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_256_PREHASH_SHAKE_128F = 'SLH_DSA_SHA2_512_256_PREHASH_SHAKE_128F';

    /** @var string The "SLH_DSA_SHA2_512_256_PREHASH_SHAKE_128S" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_256_PREHASH_SHAKE_128S = 'SLH_DSA_SHA2_512_256_PREHASH_SHAKE_128S';

    /** @var string The "SLH_DSA_SHA2_512_256_PREHASH_SHAKE_192F" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_256_PREHASH_SHAKE_192F = 'SLH_DSA_SHA2_512_256_PREHASH_SHAKE_192F';

    /** @var string The "SLH_DSA_SHA2_512_256_PREHASH_SHAKE_192S" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_256_PREHASH_SHAKE_192S = 'SLH_DSA_SHA2_512_256_PREHASH_SHAKE_192S';

    /** @var string The "SLH_DSA_SHA2_512_256_PREHASH_SHAKE_256F" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_256_PREHASH_SHAKE_256F = 'SLH_DSA_SHA2_512_256_PREHASH_SHAKE_256F';

    /** @var string The "SLH_DSA_SHA2_512_256_PREHASH_SHAKE_256S" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_256_PREHASH_SHAKE_256S = 'SLH_DSA_SHA2_512_256_PREHASH_SHAKE_256S';

    /** @var string The "SLH_DSA_SHA2_512_PREHASH_SHA2_128F" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_PREHASH_SHA2_128F = 'SLH_DSA_SHA2_512_PREHASH_SHA2_128F';

    /** @var string The "SLH_DSA_SHA2_512_PREHASH_SHA2_128S" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_PREHASH_SHA2_128S = 'SLH_DSA_SHA2_512_PREHASH_SHA2_128S';

    /** @var string The "SLH_DSA_SHA2_512_PREHASH_SHA2_192F" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_PREHASH_SHA2_192F = 'SLH_DSA_SHA2_512_PREHASH_SHA2_192F';

    /** @var string The "SLH_DSA_SHA2_512_PREHASH_SHA2_192S" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_PREHASH_SHA2_192S = 'SLH_DSA_SHA2_512_PREHASH_SHA2_192S';

    /** @var string The "SLH_DSA_SHA2_512_PREHASH_SHA2_256F" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_PREHASH_SHA2_256F = 'SLH_DSA_SHA2_512_PREHASH_SHA2_256F';

    /** @var string The "SLH_DSA_SHA2_512_PREHASH_SHA2_256S" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_PREHASH_SHA2_256S = 'SLH_DSA_SHA2_512_PREHASH_SHA2_256S';

    /** @var string The "SLH_DSA_SHA2_512_PREHASH_SHAKE_128F" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_PREHASH_SHAKE_128F = 'SLH_DSA_SHA2_512_PREHASH_SHAKE_128F';

    /** @var string The "SLH_DSA_SHA2_512_PREHASH_SHAKE_128S" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_PREHASH_SHAKE_128S = 'SLH_DSA_SHA2_512_PREHASH_SHAKE_128S';

    /** @var string The "SLH_DSA_SHA2_512_PREHASH_SHAKE_192F" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_PREHASH_SHAKE_192F = 'SLH_DSA_SHA2_512_PREHASH_SHAKE_192F';

    /** @var string The "SLH_DSA_SHA2_512_PREHASH_SHAKE_192S" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_PREHASH_SHAKE_192S = 'SLH_DSA_SHA2_512_PREHASH_SHAKE_192S';

    /** @var string The "SLH_DSA_SHA2_512_PREHASH_SHAKE_256F" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_PREHASH_SHAKE_256F = 'SLH_DSA_SHA2_512_PREHASH_SHAKE_256F';

    /** @var string The "SLH_DSA_SHA2_512_PREHASH_SHAKE_256S" algorithm. */
    public const ALG_SLH_DSA_SHA2_512_PREHASH_SHAKE_256S = 'SLH_DSA_SHA2_512_PREHASH_SHAKE_256S';

    /** @var string The "SLH_DSA_SHA3_224_PREHASH_SHA2_128F" algorithm. */
    public const ALG_SLH_DSA_SHA3_224_PREHASH_SHA2_128F = 'SLH_DSA_SHA3_224_PREHASH_SHA2_128F';

    /** @var string The "SLH_DSA_SHA3_224_PREHASH_SHA2_128S" algorithm. */
    public const ALG_SLH_DSA_SHA3_224_PREHASH_SHA2_128S = 'SLH_DSA_SHA3_224_PREHASH_SHA2_128S';

    /** @var string The "SLH_DSA_SHA3_224_PREHASH_SHA2_192F" algorithm. */
    public const ALG_SLH_DSA_SHA3_224_PREHASH_SHA2_192F = 'SLH_DSA_SHA3_224_PREHASH_SHA2_192F';

    /** @var string The "SLH_DSA_SHA3_224_PREHASH_SHA2_192S" algorithm. */
    public const ALG_SLH_DSA_SHA3_224_PREHASH_SHA2_192S = 'SLH_DSA_SHA3_224_PREHASH_SHA2_192S';

    /** @var string The "SLH_DSA_SHA3_224_PREHASH_SHA2_256F" algorithm. */
    public const ALG_SLH_DSA_SHA3_224_PREHASH_SHA2_256F = 'SLH_DSA_SHA3_224_PREHASH_SHA2_256F';

    /** @var string The "SLH_DSA_SHA3_224_PREHASH_SHA2_256S" algorithm. */
    public const ALG_SLH_DSA_SHA3_224_PREHASH_SHA2_256S = 'SLH_DSA_SHA3_224_PREHASH_SHA2_256S';

    /** @var string The "SLH_DSA_SHA3_224_PREHASH_SHAKE_128F" algorithm. */
    public const ALG_SLH_DSA_SHA3_224_PREHASH_SHAKE_128F = 'SLH_DSA_SHA3_224_PREHASH_SHAKE_128F';

    /** @var string The "SLH_DSA_SHA3_224_PREHASH_SHAKE_128S" algorithm. */
    public const ALG_SLH_DSA_SHA3_224_PREHASH_SHAKE_128S = 'SLH_DSA_SHA3_224_PREHASH_SHAKE_128S';

    /** @var string The "SLH_DSA_SHA3_224_PREHASH_SHAKE_192F" algorithm. */
    public const ALG_SLH_DSA_SHA3_224_PREHASH_SHAKE_192F = 'SLH_DSA_SHA3_224_PREHASH_SHAKE_192F';

    /** @var string The "SLH_DSA_SHA3_224_PREHASH_SHAKE_192S" algorithm. */
    public const ALG_SLH_DSA_SHA3_224_PREHASH_SHAKE_192S = 'SLH_DSA_SHA3_224_PREHASH_SHAKE_192S';

    /** @var string The "SLH_DSA_SHA3_224_PREHASH_SHAKE_256F" algorithm. */
    public const ALG_SLH_DSA_SHA3_224_PREHASH_SHAKE_256F = 'SLH_DSA_SHA3_224_PREHASH_SHAKE_256F';

    /** @var string The "SLH_DSA_SHA3_224_PREHASH_SHAKE_256S" algorithm. */
    public const ALG_SLH_DSA_SHA3_224_PREHASH_SHAKE_256S = 'SLH_DSA_SHA3_224_PREHASH_SHAKE_256S';

    /** @var string The "SLH_DSA_SHA3_256_PREHASH_SHA2_128F" algorithm. */
    public const ALG_SLH_DSA_SHA3_256_PREHASH_SHA2_128F = 'SLH_DSA_SHA3_256_PREHASH_SHA2_128F';

    /** @var string The "SLH_DSA_SHA3_256_PREHASH_SHA2_128S" algorithm. */
    public const ALG_SLH_DSA_SHA3_256_PREHASH_SHA2_128S = 'SLH_DSA_SHA3_256_PREHASH_SHA2_128S';

    /** @var string The "SLH_DSA_SHA3_256_PREHASH_SHA2_192F" algorithm. */
    public const ALG_SLH_DSA_SHA3_256_PREHASH_SHA2_192F = 'SLH_DSA_SHA3_256_PREHASH_SHA2_192F';

    /** @var string The "SLH_DSA_SHA3_256_PREHASH_SHA2_192S" algorithm. */
    public const ALG_SLH_DSA_SHA3_256_PREHASH_SHA2_192S = 'SLH_DSA_SHA3_256_PREHASH_SHA2_192S';

    /** @var string The "SLH_DSA_SHA3_256_PREHASH_SHA2_256F" algorithm. */
    public const ALG_SLH_DSA_SHA3_256_PREHASH_SHA2_256F = 'SLH_DSA_SHA3_256_PREHASH_SHA2_256F';

    /** @var string The "SLH_DSA_SHA3_256_PREHASH_SHA2_256S" algorithm. */
    public const ALG_SLH_DSA_SHA3_256_PREHASH_SHA2_256S = 'SLH_DSA_SHA3_256_PREHASH_SHA2_256S';

    /** @var string The "SLH_DSA_SHA3_256_PREHASH_SHAKE_128F" algorithm. */
    public const ALG_SLH_DSA_SHA3_256_PREHASH_SHAKE_128F = 'SLH_DSA_SHA3_256_PREHASH_SHAKE_128F';

    /** @var string The "SLH_DSA_SHA3_256_PREHASH_SHAKE_128S" algorithm. */
    public const ALG_SLH_DSA_SHA3_256_PREHASH_SHAKE_128S = 'SLH_DSA_SHA3_256_PREHASH_SHAKE_128S';

    /** @var string The "SLH_DSA_SHA3_256_PREHASH_SHAKE_192F" algorithm. */
    public const ALG_SLH_DSA_SHA3_256_PREHASH_SHAKE_192F = 'SLH_DSA_SHA3_256_PREHASH_SHAKE_192F';

    /** @var string The "SLH_DSA_SHA3_256_PREHASH_SHAKE_192S" algorithm. */
    public const ALG_SLH_DSA_SHA3_256_PREHASH_SHAKE_192S = 'SLH_DSA_SHA3_256_PREHASH_SHAKE_192S';

    /** @var string The "SLH_DSA_SHA3_256_PREHASH_SHAKE_256F" algorithm. */
    public const ALG_SLH_DSA_SHA3_256_PREHASH_SHAKE_256F = 'SLH_DSA_SHA3_256_PREHASH_SHAKE_256F';

    /** @var string The "SLH_DSA_SHA3_256_PREHASH_SHAKE_256S" algorithm. */
    public const ALG_SLH_DSA_SHA3_256_PREHASH_SHAKE_256S = 'SLH_DSA_SHA3_256_PREHASH_SHAKE_256S';

    /** @var string The "SLH_DSA_SHA3_384_PREHASH_SHA2_128F" algorithm. */
    public const ALG_SLH_DSA_SHA3_384_PREHASH_SHA2_128F = 'SLH_DSA_SHA3_384_PREHASH_SHA2_128F';

    /** @var string The "SLH_DSA_SHA3_384_PREHASH_SHA2_128S" algorithm. */
    public const ALG_SLH_DSA_SHA3_384_PREHASH_SHA2_128S = 'SLH_DSA_SHA3_384_PREHASH_SHA2_128S';

    /** @var string The "SLH_DSA_SHA3_384_PREHASH_SHA2_192F" algorithm. */
    public const ALG_SLH_DSA_SHA3_384_PREHASH_SHA2_192F = 'SLH_DSA_SHA3_384_PREHASH_SHA2_192F';

    /** @var string The "SLH_DSA_SHA3_384_PREHASH_SHA2_192S" algorithm. */
    public const ALG_SLH_DSA_SHA3_384_PREHASH_SHA2_192S = 'SLH_DSA_SHA3_384_PREHASH_SHA2_192S';

    /** @var string The "SLH_DSA_SHA3_384_PREHASH_SHA2_256F" algorithm. */
    public const ALG_SLH_DSA_SHA3_384_PREHASH_SHA2_256F = 'SLH_DSA_SHA3_384_PREHASH_SHA2_256F';

    /** @var string The "SLH_DSA_SHA3_384_PREHASH_SHA2_256S" algorithm. */
    public const ALG_SLH_DSA_SHA3_384_PREHASH_SHA2_256S = 'SLH_DSA_SHA3_384_PREHASH_SHA2_256S';

    /** @var string The "SLH_DSA_SHA3_384_PREHASH_SHAKE_128F" algorithm. */
    public const ALG_SLH_DSA_SHA3_384_PREHASH_SHAKE_128F = 'SLH_DSA_SHA3_384_PREHASH_SHAKE_128F';

    /** @var string The "SLH_DSA_SHA3_384_PREHASH_SHAKE_128S" algorithm. */
    public const ALG_SLH_DSA_SHA3_384_PREHASH_SHAKE_128S = 'SLH_DSA_SHA3_384_PREHASH_SHAKE_128S';

    /** @var string The "SLH_DSA_SHA3_384_PREHASH_SHAKE_192F" algorithm. */
    public const ALG_SLH_DSA_SHA3_384_PREHASH_SHAKE_192F = 'SLH_DSA_SHA3_384_PREHASH_SHAKE_192F';

    /** @var string The "SLH_DSA_SHA3_384_PREHASH_SHAKE_192S" algorithm. */
    public const ALG_SLH_DSA_SHA3_384_PREHASH_SHAKE_192S = 'SLH_DSA_SHA3_384_PREHASH_SHAKE_192S';

    /** @var string The "SLH_DSA_SHA3_384_PREHASH_SHAKE_256F" algorithm. */
    public const ALG_SLH_DSA_SHA3_384_PREHASH_SHAKE_256F = 'SLH_DSA_SHA3_384_PREHASH_SHAKE_256F';

    /** @var string The "SLH_DSA_SHA3_384_PREHASH_SHAKE_256S" algorithm. */
    public const ALG_SLH_DSA_SHA3_384_PREHASH_SHAKE_256S = 'SLH_DSA_SHA3_384_PREHASH_SHAKE_256S';

    /** @var string The "SLH_DSA_SHA3_512_PREHASH_SHA2_128F" algorithm. */
    public const ALG_SLH_DSA_SHA3_512_PREHASH_SHA2_128F = 'SLH_DSA_SHA3_512_PREHASH_SHA2_128F';

    /** @var string The "SLH_DSA_SHA3_512_PREHASH_SHA2_128S" algorithm. */
    public const ALG_SLH_DSA_SHA3_512_PREHASH_SHA2_128S = 'SLH_DSA_SHA3_512_PREHASH_SHA2_128S';

    /** @var string The "SLH_DSA_SHA3_512_PREHASH_SHA2_192F" algorithm. */
    public const ALG_SLH_DSA_SHA3_512_PREHASH_SHA2_192F = 'SLH_DSA_SHA3_512_PREHASH_SHA2_192F';

    /** @var string The "SLH_DSA_SHA3_512_PREHASH_SHA2_192S" algorithm. */
    public const ALG_SLH_DSA_SHA3_512_PREHASH_SHA2_192S = 'SLH_DSA_SHA3_512_PREHASH_SHA2_192S';

    /** @var string The "SLH_DSA_SHA3_512_PREHASH_SHA2_256F" algorithm. */
    public const ALG_SLH_DSA_SHA3_512_PREHASH_SHA2_256F = 'SLH_DSA_SHA3_512_PREHASH_SHA2_256F';

    /** @var string The "SLH_DSA_SHA3_512_PREHASH_SHA2_256S" algorithm. */
    public const ALG_SLH_DSA_SHA3_512_PREHASH_SHA2_256S = 'SLH_DSA_SHA3_512_PREHASH_SHA2_256S';

    /** @var string The "SLH_DSA_SHA3_512_PREHASH_SHAKE_128F" algorithm. */
    public const ALG_SLH_DSA_SHA3_512_PREHASH_SHAKE_128F = 'SLH_DSA_SHA3_512_PREHASH_SHAKE_128F';

    /** @var string The "SLH_DSA_SHA3_512_PREHASH_SHAKE_128S" algorithm. */
    public const ALG_SLH_DSA_SHA3_512_PREHASH_SHAKE_128S = 'SLH_DSA_SHA3_512_PREHASH_SHAKE_128S';

    /** @var string The "SLH_DSA_SHA3_512_PREHASH_SHAKE_192F" algorithm. */
    public const ALG_SLH_DSA_SHA3_512_PREHASH_SHAKE_192F = 'SLH_DSA_SHA3_512_PREHASH_SHAKE_192F';

    /** @var string The "SLH_DSA_SHA3_512_PREHASH_SHAKE_192S" algorithm. */
    public const ALG_SLH_DSA_SHA3_512_PREHASH_SHAKE_192S = 'SLH_DSA_SHA3_512_PREHASH_SHAKE_192S';

    /** @var string The "SLH_DSA_SHA3_512_PREHASH_SHAKE_256F" algorithm. */
    public const ALG_SLH_DSA_SHA3_512_PREHASH_SHAKE_256F = 'SLH_DSA_SHA3_512_PREHASH_SHAKE_256F';

    /** @var string The "SLH_DSA_SHA3_512_PREHASH_SHAKE_256S" algorithm. */
    public const ALG_SLH_DSA_SHA3_512_PREHASH_SHAKE_256S = 'SLH_DSA_SHA3_512_PREHASH_SHAKE_256S';

    /** @var string The "SLH_DSA_SHAKE_128_PREHASH_SHA2_128F" algorithm. */
    public const ALG_SLH_DSA_SHAKE_128_PREHASH_SHA2_128F = 'SLH_DSA_SHAKE_128_PREHASH_SHA2_128F';

    /** @var string The "SLH_DSA_SHAKE_128_PREHASH_SHA2_128S" algorithm. */
    public const ALG_SLH_DSA_SHAKE_128_PREHASH_SHA2_128S = 'SLH_DSA_SHAKE_128_PREHASH_SHA2_128S';

    /** @var string The "SLH_DSA_SHAKE_128_PREHASH_SHA2_192F" algorithm. */
    public const ALG_SLH_DSA_SHAKE_128_PREHASH_SHA2_192F = 'SLH_DSA_SHAKE_128_PREHASH_SHA2_192F';

    /** @var string The "SLH_DSA_SHAKE_128_PREHASH_SHA2_192S" algorithm. */
    public const ALG_SLH_DSA_SHAKE_128_PREHASH_SHA2_192S = 'SLH_DSA_SHAKE_128_PREHASH_SHA2_192S';

    /** @var string The "SLH_DSA_SHAKE_128_PREHASH_SHA2_256F" algorithm. */
    public const ALG_SLH_DSA_SHAKE_128_PREHASH_SHA2_256F = 'SLH_DSA_SHAKE_128_PREHASH_SHA2_256F';

    /** @var string The "SLH_DSA_SHAKE_128_PREHASH_SHA2_256S" algorithm. */
    public const ALG_SLH_DSA_SHAKE_128_PREHASH_SHA2_256S = 'SLH_DSA_SHAKE_128_PREHASH_SHA2_256S';

    /** @var string The "SLH_DSA_SHAKE_128_PREHASH_SHAKE_128F" algorithm. */
    public const ALG_SLH_DSA_SHAKE_128_PREHASH_SHAKE_128F = 'SLH_DSA_SHAKE_128_PREHASH_SHAKE_128F';

    /** @var string The "SLH_DSA_SHAKE_128_PREHASH_SHAKE_128S" algorithm. */
    public const ALG_SLH_DSA_SHAKE_128_PREHASH_SHAKE_128S = 'SLH_DSA_SHAKE_128_PREHASH_SHAKE_128S';

    /** @var string The "SLH_DSA_SHAKE_128_PREHASH_SHAKE_192F" algorithm. */
    public const ALG_SLH_DSA_SHAKE_128_PREHASH_SHAKE_192F = 'SLH_DSA_SHAKE_128_PREHASH_SHAKE_192F';

    /** @var string The "SLH_DSA_SHAKE_128_PREHASH_SHAKE_192S" algorithm. */
    public const ALG_SLH_DSA_SHAKE_128_PREHASH_SHAKE_192S = 'SLH_DSA_SHAKE_128_PREHASH_SHAKE_192S';

    /** @var string The "SLH_DSA_SHAKE_128_PREHASH_SHAKE_256F" algorithm. */
    public const ALG_SLH_DSA_SHAKE_128_PREHASH_SHAKE_256F = 'SLH_DSA_SHAKE_128_PREHASH_SHAKE_256F';

    /** @var string The "SLH_DSA_SHAKE_128_PREHASH_SHAKE_256S" algorithm. */
    public const ALG_SLH_DSA_SHAKE_128_PREHASH_SHAKE_256S = 'SLH_DSA_SHAKE_128_PREHASH_SHAKE_256S';

    /** @var string The "SLH_DSA_SHAKE_256_PREHASH_SHA2_128F" algorithm. */
    public const ALG_SLH_DSA_SHAKE_256_PREHASH_SHA2_128F = 'SLH_DSA_SHAKE_256_PREHASH_SHA2_128F';

    /** @var string The "SLH_DSA_SHAKE_256_PREHASH_SHA2_128S" algorithm. */
    public const ALG_SLH_DSA_SHAKE_256_PREHASH_SHA2_128S = 'SLH_DSA_SHAKE_256_PREHASH_SHA2_128S';

    /** @var string The "SLH_DSA_SHAKE_256_PREHASH_SHA2_192F" algorithm. */
    public const ALG_SLH_DSA_SHAKE_256_PREHASH_SHA2_192F = 'SLH_DSA_SHAKE_256_PREHASH_SHA2_192F';

    /** @var string The "SLH_DSA_SHAKE_256_PREHASH_SHA2_192S" algorithm. */
    public const ALG_SLH_DSA_SHAKE_256_PREHASH_SHA2_192S = 'SLH_DSA_SHAKE_256_PREHASH_SHA2_192S';

    /** @var string The "SLH_DSA_SHAKE_256_PREHASH_SHA2_256F" algorithm. */
    public const ALG_SLH_DSA_SHAKE_256_PREHASH_SHA2_256F = 'SLH_DSA_SHAKE_256_PREHASH_SHA2_256F';

    /** @var string The "SLH_DSA_SHAKE_256_PREHASH_SHA2_256S" algorithm. */
    public const ALG_SLH_DSA_SHAKE_256_PREHASH_SHA2_256S = 'SLH_DSA_SHAKE_256_PREHASH_SHA2_256S';

    /** @var string The "SLH_DSA_SHAKE_256_PREHASH_SHAKE_128F" algorithm. */
    public const ALG_SLH_DSA_SHAKE_256_PREHASH_SHAKE_128F = 'SLH_DSA_SHAKE_256_PREHASH_SHAKE_128F';

    /** @var string The "SLH_DSA_SHAKE_256_PREHASH_SHAKE_128S" algorithm. */
    public const ALG_SLH_DSA_SHAKE_256_PREHASH_SHAKE_128S = 'SLH_DSA_SHAKE_256_PREHASH_SHAKE_128S';

    /** @var string The "SLH_DSA_SHAKE_256_PREHASH_SHAKE_192F" algorithm. */
    public const ALG_SLH_DSA_SHAKE_256_PREHASH_SHAKE_192F = 'SLH_DSA_SHAKE_256_PREHASH_SHAKE_192F';

    /** @var string The "SLH_DSA_SHAKE_256_PREHASH_SHAKE_192S" algorithm. */
    public const ALG_SLH_DSA_SHAKE_256_PREHASH_SHAKE_192S = 'SLH_DSA_SHAKE_256_PREHASH_SHAKE_192S';

    /** @var string The "SLH_DSA_SHAKE_256_PREHASH_SHAKE_256F" algorithm. */
    public const ALG_SLH_DSA_SHAKE_256_PREHASH_SHAKE_256F = 'SLH_DSA_SHAKE_256_PREHASH_SHAKE_256F';

    /** @var string The "SLH_DSA_SHAKE_256_PREHASH_SHAKE_256S" algorithm. */
    public const ALG_SLH_DSA_SHAKE_256_PREHASH_SHAKE_256S = 'SLH_DSA_SHAKE_256_PREHASH_SHAKE_256S';

    /** @var string The "SNOVA_24_5_4" algorithm. */
    public const ALG_SNOVA_24_5_4 = 'SNOVA_24_5_4';

    /** @var string The "SNOVA_24_5_4_esk" algorithm. */
    public const ALG_SNOVA_24_5_4_ESK = 'SNOVA_24_5_4_esk';

    /** @var string The "SNOVA_24_5_4_SHAKE" algorithm. */
    public const ALG_SNOVA_24_5_4_SHAKE = 'SNOVA_24_5_4_SHAKE';

    /** @var string The "SNOVA_24_5_4_SHAKE_esk" algorithm. */
    public const ALG_SNOVA_24_5_4_SHAKE_ESK = 'SNOVA_24_5_4_SHAKE_esk';

    /** @var string The "SNOVA_24_5_5" algorithm. */
    public const ALG_SNOVA_24_5_5 = 'SNOVA_24_5_5';

    /** @var string The "SNOVA_25_8_3" algorithm. */
    public const ALG_SNOVA_25_8_3 = 'SNOVA_25_8_3';

    /** @var string The "SNOVA_29_6_5" algorithm. */
    public const ALG_SNOVA_29_6_5 = 'SNOVA_29_6_5';

    /** @var string The "SNOVA_37_17_2" algorithm. */
    public const ALG_SNOVA_37_17_2 = 'SNOVA_37_17_2';

    /** @var string The "SNOVA_37_8_4" algorithm. */
    public const ALG_SNOVA_37_8_4 = 'SNOVA_37_8_4';

    /** @var string The "SNOVA_49_11_3" algorithm. */
    public const ALG_SNOVA_49_11_3 = 'SNOVA_49_11_3';

    /** @var string The "SNOVA_56_25_2" algorithm. */
    public const ALG_SNOVA_56_25_2 = 'SNOVA_56_25_2';

    /** @var string The "SNOVA_60_10_4" algorithm. */
    public const ALG_SNOVA_60_10_4 = 'SNOVA_60_10_4';

    /**
     * @param string $algorithm
     */
    public function __construct(string $algorithm) {}

    /**
     * @return array
     */
    public function keypair(): array {}

    /**
     * @param string $message
     * @param string $secretKey
     * @return string
     */
    public function sign(string $message, string $secretKey): string {}

    /**
     * @param string $message
     * @param string $signature
     * @param string $publicKey
     * @return bool
     */
    public function verify(string $message, string $signature, string $publicKey): bool {}

    /**
     * @return array
     */
    public function details(): array {}

    /**
     * @return array
     */
    public static function algorithms(): array {}

}
